### ISSUE TITLE
Cannot use the provided models.

### ISSUE THREAD

**Issue by LePhasme** [leapmotion/leapjs-rigged-hand#18]
Before modeling my own rigged hand, as a Blender newbie I tried to open the models included in this plugin in order to understand how they were made and figure out the path I have to follow (since it's unfortunately impossible to re-import the working JSON file in Blender).

But none of the models here seems to work (using Blender 2.75a and Three.js r71):

- **/models/Game Quality Hand/Arm_Hand**: not the same model as the one actually used by the plugin (longer forearm). The .dae files can't be imported (the scene remains empty, I see no error) and the geometry of the .fbx files is screwed up (especially around the thumb).
- **/models/Game Quality Hand/Handsolo**: seems to be the right model, but the `"Leapmotion_Handsolo_Rig_RIght.dae"` file is completely unrelated to the left one (another model, both hands, not rigged). The .fbx files look right, but the bones are messy (then again, most notably in relation to the thumb). Couldn't use them back in Three.js (using various settings: fingers are all displayed with weird angles, the palm is upside-down, etc.).
- **/models/Revamped Hand**: not the same model (nothing beyond the wrist). I tried to export it to Three.js using various settings, but then again it doesn't fit in the data model. The `"handrevamp_hipoly_rig_left.dae"` file is almost twice as large as the right one, which looks suspicious (missing data?).
- **/models/Test Rig**: not the same model. The `"Leapmotion_Basehand_Rig_Left.dae"` file is almost empty (less than 5Kb). The other file (as well as both the .fbx files) look good, but then again, once exported, I always fail to use them in Three.js (wrong angles, the geometry tends to be torn apart, etc.).

What am I doing wrong? Are there some steps and settings I'm missing?

Thanks in advance for your advice.

**Comment by codemercenary** [comment]
Looks like it's been awhile since this was in active development, we might have bitrot on our hands.  @pehrlich, any insights?

**Comment by LePhasme** [comment]
Hi, thanks to have a look at this issue.

My motive was also to fix the original model as I noticed a tiny "hole" between the middle and the ring finger (here in the center of the red circle):
![hole](https://cloud.githubusercontent.com/assets/214796/9931939/3ce646a8-5d40-11e5-9a1a-8943b0750f68.png)

It would be beneficial for the community to have a clean "template" to work from. I would be pleased to contribute to it, btw.

I tried to use a hand built with MakeHuman, but the task of making it fit in the Leap Motion data model has been insurmountable so far :(

**Comment by codemercenary** [comment]
Interesting.  Well, if you can fix the issue yourself then certainly we can accept and merge a pull request.  That little hole you have selected looks like a gap in the mesh; I'm not quite sure of the best way to fix something like that.

And yes, rigging a human hand from our data can be pretty tough, it's a lot of glue logic.

**Comment by LePhasme** [comment]
That's precisely why I tried to "get my hand" on the original model :)
Fixing a model is something I can handle, but the whole rigging thing is still way beyond my knowledge right now...
I was hoping that the working JSON data could be imported back in Blender, but it seems this feature is not going to happen soon.

**Comment by codemercenary** [comment]
I'd have to defer to Peter on this one, he's the current maintainer.

**Comment by pehrlich** [comment]
Let me first direct your attention to the wiki, which may help while I attempt to repro the same process myself. https://github.com/leapmotion/leapjs-rigged-hand/wiki/Creating-Rigged-Hands

**Comment by SebCourvoisier4D** [comment]
Hi Peter, I tried many times to follow the steps described in the wiki page (starting from "Maya -> Blender -> THREE.js"), but the resulting JSON file never behaves as the original one. So either I'm missing a step, or the DAE file is not the proper one.

**Comment by pehrlich** [comment]
Just a quick update - I was able to load up the left hand .dae `/models/Game Quality Hand/Handsolo/Leapmotion_Handsolo_Rig_Left.dae` in to Blender, and successfully export it to THREE.js and use it in the project.  Getting some errors going from Maya/FBX to Blender/DAE - something to look in to on monday.

I've also noticed that with the Bones checkbox checked in the THREE.js exporter, there are base quaternions and positions for every bone - perhaps that can be used by the JS to accept skeletons in more natural rest poses.

**Comment by SebCourvoisier4D** [comment]
Hi Peter, thanks for the update.

I also managed to import and export the left hand, using the following settings when importing the DAE file:

<img width="232" alt="import1setting" src="https://cloud.githubusercontent.com/assets/3353774/9975679/4bf0a37e-5ec5-11e5-8654-8e6a76b4b5f3.png">

In the wiki page you mention _"Make sure that the `import units` box is checked"_, but it looks like that the two `Armature Options` need to be checked too.

<img width="415" alt="import1result" src="https://cloud.githubusercontent.com/assets/3353774/9975734/4dad2e74-5ec7-11e5-8f6e-d6ec72870f85.png"> Tada!

And for the export:

<img width="219" alt="export1setting" src="https://cloud.githubusercontent.com/assets/3353774/9975714/b55423ee-5ec6-11e5-9939-5be28a5de73c.png">

Blender keeps forgetting my settings, even if I press "Save Settings", so I may have missed something in the course of the numerous tests and trials I made the past few days. 

Now I'll try to fix the mesh and recreate the right hand from the left one (will it be easy? I have no idea...).

**Comment by LePhasme** [comment]
See https://github.com/leapmotion/leapjs-rigged-hand/pull/19

**Comment by pehrlich** [comment]
Good stuff!  I've pushed to master with a few corrections: 
 - The Left hand fbx no longer has references to unavailable assets.
 - The right.dae now actually is as named [raw link](https://github.com/leapmotion/leapjs-rigged-hand/raw/master/models/Game%20Quality%20Hand/Handsolo/Leapmotion_Handsolo_Rig_RIght.dae)
 - The pair of hands misnamed as right hand, have been moved in to
other.

**Comment by codemercenary** [comment]
@LePhasme any further feedback?

**Comment by LePhasme** [comment]
Hi, everything is fine! Many thanks!
