### ISSUE TITLE
Rendering graphics to a customized canvas with a specific id

### ISSUE THREAD

**Issue by daqo** [leapmotion/leapjs-rigged-hand#21]
Is there a way to render the canvas into a customized canvas with a specific id?
Some thing like:
```
<canvas id="scene"></canvas>
```

**Comment by pehrlich** [comment]
You can pass in a custom `renderer` or a `parent` scene - https://github.com/leapmotion/leapjs-rigged-hand/blob/master/src/leap.rigged-hand.coffee#L10
